#!/bin/bash

function createEci() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/eci.election.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/eci.election.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-eci --tls.certfiles "${PWD}/organizations/fabric-ca/eci/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-eci.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-eci.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-eci.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-eci.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/eci.election.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy eci's CA cert to eci's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/eci.election.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/eci/ca-cert.pem" "${PWD}/organizations/peerOrganizations/eci.election.com/msp/tlscacerts/ca.crt"

  # Copy eci's CA cert to eci's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/eci.election.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/eci/ca-cert.pem" "${PWD}/organizations/peerOrganizations/eci.election.com/tlsca/tlsca.eci.election.com-cert.pem"

  # Copy eci's CA cert to eci's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/eci.election.com/ca"
  cp "${PWD}/organizations/fabric-ca/eci/ca-cert.pem" "${PWD}/organizations/peerOrganizations/eci.election.com/ca/ca.eci.election.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-eci --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/eci/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-eci --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/eci/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-eci --id.name eciadmin --id.secret eciadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/eci/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-eci -M "${PWD}/organizations/peerOrganizations/eci.election.com/peers/peer0.eci.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/eci/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/eci.election.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/eci.election.com/peers/peer0.eci.election.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-eci -M "${PWD}/organizations/peerOrganizations/eci.election.com/peers/peer0.eci.election.com/tls" --enrollment.profile tls --csr.hosts peer0.eci.election.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/eci/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/eci.election.com/peers/peer0.eci.election.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/eci.election.com/peers/peer0.eci.election.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/eci.election.com/peers/peer0.eci.election.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/eci.election.com/peers/peer0.eci.election.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/eci.election.com/peers/peer0.eci.election.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/eci.election.com/peers/peer0.eci.election.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-eci -M "${PWD}/organizations/peerOrganizations/eci.election.com/users/User1@eci.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/eci/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/eci.election.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/eci.election.com/users/User1@eci.election.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://eciadmin:eciadminpw@localhost:7054 --caname ca-eci -M "${PWD}/organizations/peerOrganizations/eci.election.com/users/Admin@eci.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/eci/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/eci.election.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/eci.election.com/users/Admin@eci.election.com/msp/config.yaml"
}

function createUidai() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/uidai.election.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/uidai.election.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-uidai --tls.certfiles "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-uidai.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-uidai.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-uidai.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-uidai.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/uidai.election.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy uidai's CA cert to uidai's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/uidai.election.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem" "${PWD}/organizations/peerOrganizations/uidai.election.com/msp/tlscacerts/ca.crt"

  # Copy uidai's CA cert to uidai's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/uidai.election.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem" "${PWD}/organizations/peerOrganizations/uidai.election.com/tlsca/tlsca.uidai.election.com-cert.pem"

  # Copy uidai's CA cert to uidai's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/uidai.election.com/ca"
  cp "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem" "${PWD}/organizations/peerOrganizations/uidai.election.com/ca/ca.uidai.election.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-uidai --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-uidai --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-uidai --id.name uidaiadmin --id.secret uidaiadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-uidai -M "${PWD}/organizations/peerOrganizations/uidai.election.com/peers/peer0.uidai.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/uidai.election.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/uidai.election.com/peers/peer0.uidai.election.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-uidai -M "${PWD}/organizations/peerOrganizations/uidai.election.com/peers/peer0.uidai.election.com/tls" --enrollment.profile tls --csr.hosts peer0.uidai.election.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/uidai.election.com/peers/peer0.uidai.election.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/uidai.election.com/peers/peer0.uidai.election.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/uidai.election.com/peers/peer0.uidai.election.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/uidai.election.com/peers/peer0.uidai.election.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/uidai.election.com/peers/peer0.uidai.election.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/uidai.election.com/peers/peer0.uidai.election.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-uidai -M "${PWD}/organizations/peerOrganizations/uidai.election.com/users/User1@uidai.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/uidai.election.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/uidai.election.com/users/User1@uidai.election.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://uidaiadmin:uidaiadminpw@localhost:8054 --caname ca-uidai -M "${PWD}/organizations/peerOrganizations/uidai.election.com/users/Admin@uidai.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/uidai/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/uidai.election.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/uidai.election.com/users/Admin@uidai.election.com/msp/config.yaml"
}


function createParty() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/party.election.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/party.election.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-party --tls.certfiles "${PWD}/organizations/fabric-ca/party/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-party.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-party.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-party.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-party.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/party.election.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy party's CA cert to party's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/party.election.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/party/ca-cert.pem" "${PWD}/organizations/peerOrganizations/party.election.com/msp/tlscacerts/ca.crt"

  # Copy party's CA cert to party's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/party.election.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/party/ca-cert.pem" "${PWD}/organizations/peerOrganizations/party.election.com/tlsca/tlsca.party.election.com-cert.pem"

  # Copy party's CA cert to party's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/party.election.com/ca"
  cp "${PWD}/organizations/fabric-ca/party/ca-cert.pem" "${PWD}/organizations/peerOrganizations/party.election.com/ca/ca.party.election.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-party --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/party/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-party --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/party/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-party --id.name partyadmin --id.secret partyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/party/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-party -M "${PWD}/organizations/peerOrganizations/party.election.com/peers/peer0.party.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/party/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/party.election.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/party.election.com/peers/peer0.party.election.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-party -M "${PWD}/organizations/peerOrganizations/party.election.com/peers/peer0.party.election.com/tls" --enrollment.profile tls --csr.hosts peer0.party.election.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/party/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/party.election.com/peers/peer0.party.election.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/party.election.com/peers/peer0.party.election.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/party.election.com/peers/peer0.party.election.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/party.election.com/peers/peer0.party.election.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/party.election.com/peers/peer0.party.election.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/party.election.com/peers/peer0.party.election.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-party -M "${PWD}/organizations/peerOrganizations/party.election.com/users/User1@party.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/party/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/party.election.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/party.election.com/users/User1@party.election.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://partyadmin:partyadminpw@localhost:11054 --caname ca-party -M "${PWD}/organizations/peerOrganizations/party.election.com/users/Admin@party.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/party/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/party.election.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/party.election.com/users/Admin@party.election.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/election.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/election.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/election.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/election.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/election.com/msp/tlscacerts/tlsca.election.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/election.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/election.com/tlsca/tlsca.election.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/election.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/tls" --enrollment.profile tls --csr.hosts orderer.election.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/election.com/orderers/orderer.election.com/msp/tlscacerts/tlsca.election.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/election.com/users/Admin@election.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/election.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/election.com/users/Admin@election.com/msp/config.yaml"
}

createEci
createUidai
createParty
createOrderer